version: '3.8'
services:
  api:
    build: .
    ports:
      - "5001:5001"
    depends_on:
      - mongo
    env_file:
      - .env # This tells Docker Compose to use variables from .env
  mongo:
    image: mongo:latest
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
volumes:
  mongodata:
